apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: capstone
  labels:
    app: mysql-config
data:
  MYSQL_DATABASE: indigo
  initdb.sql: |
    use indigo;
    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    SET AUTOCOMMIT = 0;
    START TRANSACTION;
    SET time_zone = "+00:00";
    DROP TABLE IF EXISTS `student`;
    CREATE TABLE IF NOT EXISTS `student` (`student_id` int(11) NOT NULL AUTO_INCREMENT,`student_branch` varchar(255) DEFAULT NULL,`student_email` varchar(255) DEFAULT NULL,`student_name` varchar(255) DEFAULT NULL,PRIMARY KEY (`student_id`)) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;
    INSERT INTO `student` (`student_id`, `student_branch`, `student_email`, `student_name`) VALUES(2, 'MCA', 'dolly@gmail.com', 'Dolly'),(3, 'B-Tech', 'sonoo@gmail.com', 'sonoo');
    COMMIT;
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log-bin
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
